channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - fsspec
  - ipywidgets>=7.0.0
  - scikit-image
  - zarr
  - requests
  - aiohttp
  - dask
  # - napari
  # - numba
  # - pip:
  #   - ome_zarr
  # - imjoy>=0.10.10
  # - imjoy-rpc>=0.2.30